# Generated by Django 6.0.2 on 2026-03-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='buscando_partida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ultima_actividad',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
