# Generated by Django 6.0.2 on 2026-03-02 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0002_alter_disparo_id_alter_disposicionbarcos_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disparo',
            name='hundido',
        ),
        migrations.RemoveField(
            model_name='disparo',
            name='impacto',
        ),
        migrations.AddField(
            model_name='disparo',
            name='resultado',
            field=models.CharField(default='Sin resultado', max_length=20),
        ),
        migrations.CreateModel(
            name='Barco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('tamaño', models.IntegerField()),
                ('vida', models.IntegerField()),
                ('hundido', models.BooleanField(default=False)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partida.partida')),
            ],
        ),
    ]
