# Generated by Django 6.0.2 on 2026-03-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0003_remove_disparo_hundido_remove_disparo_impacto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barco',
            name='posiciones',
            field=models.JSONField(default=list),
        ),
    ]
