# Generated by Django 6.0.1 on 2026-03-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0006_alter_barco_id_alter_disparo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disparo',
            name='resultado',
            field=models.CharField(default='Sin resultado', max_length=100),
        ),
    ]
