# Generated by Django 6.0.1 on 2026-03-07 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=False)),
                ('retado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retado', to=settings.AUTH_USER_MODEL)),
                ('retador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
