# Generated by Django 6.0.1 on 2026-03-07 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_perfil_buscando_partida_perfil_ultima_actividad'),
        ('inicial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reto',
            name='retado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retado', to='admin_panel.perfil'),
        ),
        migrations.AlterField(
            model_name='reto',
            name='retador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retador', to='admin_panel.perfil'),
        ),
    ]
